### ISSUE TITLE
Supporting the optional flag

### ISSUE THREAD

**Issue by pbiggar** [janestreet/ppx_bin_prot#10]
ppx_deriving supports an `optional` flag. From their docs:

> It's possible to make deriving ignore a missing plugin rather than raising an error by passing an optional = true option, for example, to enable conditional compilation:
>
>```
>type addr = string * int
>[@@deriving yojson { optional = true }]
>```

This works well for their builtins, but doesn't seem to work for bin_io - which is making writing platform independent code difficult. Would you be able to support it?

**Comment by hhugo** [comment]
I believe this issue belongs to https://github.com/ocaml-ppx/ppxlib

**Comment by pbiggar** [comment]
Thanks @hhugo, will report it there.

**Comment by aalekseyev** [comment]
Closing this one.
